myapp/app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'app'
urlpatterns = [
    path('', views.index),
    # is a class based view needs .as_view()
    path('products/', views.ProductListView.as_view(), name="products"),
    path('products/<int:pk>/', views.ProductDetailView.as_view(),
         name="product_detail"),
    path('products/add/', views.ProductCreateView.as_view(), name="add_product"),
    path('products/update/<int:pk>/',
         views.ProductUpdateView.as_view(), name="update_product"),
    path('products/delete/<int:pk>/',
         views.ProductDeleteView.as_view(), name="delete_product"),
    path('products/search/', views.SearchView.as_view(), name='search'),
    path('products/mylistings', views.my_listing, name="mylistings"),

]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(
        template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('createprofile/', views.create_profile, name='createprofile'),
    path('sellerprofile/<int:id>/', views.seller_profile, name='sellerprofile'),
]

myapp/app/templates/app/addproduct.html
{% extends 'app/base.html' %} {% block content %}
<h1 class="text-2xl m-10 font-bold">➕ Add Product</h1>
<form
	class="w-3/5 bg-white shadow-md m-10 px-8 py-8"
	method="POST"
	enctype="multipart/form-data"
>
	{% csrf_token %}
	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2" for=""
			>Product Name</label
		>
		<input
			class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-700"
			placeholder="Computer"
			type="text"
			name="name"
			id="name"
		/>
	</div>
	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2" for="">
			Product Price</label
		>
		<input
			class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-700"
			placeholder=" 1000"
			type="text"
			name="price"
			id="price"
		/>
	</div>
	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2" for="">
			Product Description</label
		>
		<input
			class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-700"
			placeholder=" This is a Computer"
			type="text"
			name="desc"
			id="desc"
		/>
	</div>
	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2" for="">
			Product Image
		</label>
		<input
			class="py-2"
			type="file"
			accept="image/*"
			name="upload"
			id="upload"
		/>
	</div>
	<div class="mb-4">
		<input
			class="bg-green-500 text-white px-5 py-2"
			type="submit"
			name="Add Product"
			value="Add Product"
			id=""
		/>
	</div>
</form>
{% endblock %}

myapp/app/templates/app/base.html
{% load static %}
<html>
	<head>
		<link rel="stylesheet" href="{% static 'app/styles.css' %}" />
	</head>
	<body>
		<nav class="bg-white shadow-lg">
			<div class="max-w-6xl mx-auto px-4">
				<div class="flex justify-between">
					<div class="flex space-x-7 items-center">
						<div>
							<a
								href="{% url 'app:products' %}"
								class="flex items-center"
							>
								<img
									class="h-8 w-8"
									src="{% static 'app/images/icon.png' %}"
									alt="Logo"
								/>
								<span
									class="text-gray-500 font-semibold text-lg"
									>Buy&Sell</span
								>
							</a>
						</div>
						<div class="flex space-x-1 items-center">
							<a
								href="{% url 'app:products' %}"
								class="py-4 px-10 text-gray-500 font-semibold {% if request.resolver_match.url_name == 'products' %}border-b-4 border-green-500{% endif %}"
								>Home</a
							>
							<a
								href="{% url 'app:add_product' %}"
								class="py-4 px-10 text-gray-500 font-semibold {% if request.resolver_match.url_name == 'add_product' %}border-b-4 border-green-500{% endif %}"
								>Post Ad</a
							>
							<a
								href="{% url 'app:products' %}"
								class="py-4 px-10 text-gray-500 font-semibold"
								>View products</a
							>
							{% if user.is_authenticated %}
							<a
								href="{% url 'users:logout' %}"
								class="py-4 px-10 text-gray-500 font-semibold{% if request.resolver_match.url_name == 'logout' %}border-b-4 border-green-500{% endif %}"
								>Logout</a
							>
							<a
								class="py-4 px-10 text-gray-500 font-semibold {% if request.resolver_match.url_name == 'profile' %}border-b-4 border-green-500{% endif %}"
								href="{% url 'users:profile' %}"
								>Profile</a
							>
							<a
								class="py-4 px-10 text-gray-500 font-semibold {% if request.resolver_match.url_name == 'mylistings' %}border-b-4 border-green-500{% endif %}"
								href="{% url 'app:mylistings' %}"
								>My Listings</a
							>

							{% else %}
							<a
								href="{% url 'users:login' %}"
								class="py-4 px-20 text-gray-500 font-semibold {% if request.resolver_match.url_name == 'login' %}border-b-4 border-green-500{% endif %}"
								>Login</a
							>
							{% endif %}
							<form
								action="{% url 'app:search' %}"
								method="GET"
								class="flex items-center"
							>
								<input
									class="py-2 px-3 text-gray-700 leading-tight focus:outline-none"
									type="search"
									placeholder="Search"
									aria-label="Search"
									name="q"
								/>
								<button
									type="submit"
									class="bg-green-500 text-white py-2 px-4 rounded-md hover:bg-green-600 focus:outline-none ml-2"
								>
									Search
								</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</nav>

		{% block content %} {% endblock %}
	</body>
</html>

myapp/app/templates/app/delete.html
{% extends 'app/base.html' %} {% block content %}
<h1>Delete Product</h1>
<form
	method="post"
	class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4"
>
	{% csrf_token %}
	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2">
			Do you want to delete this item ?</label>
	</div>
	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2">
			{{product.name}}
		</label>
	</div>
	<div class="mb-4">
		<img src="{{product.image.url}}" alt="" />
	</div>
	<input
		class="bg-red-500 text-white px-5 py-2"
		type="submit"
		name="Confirm"
		value="Confirm"
	/>
	<a class="bg-green-500 text-white px-5 py-3" href="{% url 'app:products' %}"
		>Cancel</a
	>
</form>
{% if form.errors %}
	{% for field in form %}
		{% for error in field.errors %}
			<p> {{ error }} </p>
        {% endfor %}
    {% endfor %}
{% endif %}
{% endblock %}

myapp/app/templates/app/detail.html
{% extends 'app/base.html' %} {% block content %}
<div class="flex p-10">
	<img class="w-1/3" src="{{product.image.url}}" alt="" />
	<div class="w-2/3 text-xl ml-10 mt-10">
		<div class="mt-5">{{product.name}}</div>
		<div class="mt-5 text-green-500">$ {{product.price}}</div>
		<div class="mt-5 text-gray-700">{{product.desc}}</div>
		<div class="mt-5 text-gray-700">
			Posted By:
			<a href="{% url 'users:sellerprofile' product.seller_name.id %}"
				>{{product.seller_name}}</a
			>
		</div>
		<div class="mt-5 text-gray-700">
			Contact: {{product.seller_name.profile.contact_number}}
		</div>
	</div>
</div>

{% endblock %}

myapp/app/templates/app/index.html
{% extends 'app/base.html' %} {% load static %} {% block content %}
<!--Site Hero starts Here-->
<main
	class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
	<div class="sm:text-center lg:text-left">
		<h1
			class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
			<span class="block xl:inline">Premium Products</span>
			<span class="block text-green-500 xl:inline"
				>Non-Premiun Prices</span
			>
		</h1>
		<p
			class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
			Get the best Products across the globe. Free shipping internationally
		</p>
	</div>
</main>
<!--Site Hero ends Here-->
<div class="flex mt-5 p-10 justify-center">
	<h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">
		Recent Products
	</h2>
</div>

<div
	class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-5">
	<!--card 1-->
	{% for product in products %}
	<a href="{% url 'app:product_detail' product.id %}">
		<div class="rounded overflow-hidden shadow-lg h-100">
			<img class="w-full h-48 object-contain"  src="{{product.image.url}}" alt="" />
			<div class="px-6 py-4">
				<div class="font-bold text-xl mb-2">{{product.name}}</div>
				<div class="font-bold text-xl text-green-500 mb-2">
					$ {{product.price}}
				</div>
				<div class="font-bold mb-2">
					Posted By:
					<span class="text-indigo-500">{{product.seller_name}}</span>
				</div>
				<p class="text-gray-700 text-base">{{product.desc}}</p>
			</div>
		</div>
	</a>
	{% endfor %}
</div>
<!--Pagination Code starts here -->
<div class="pagination flex justify-center items-center mb-20">
	<span>
		{% if page_obj.has_previous %}
		<a
			class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10"
			href="?page=1"
			>First</a
		>
		<a
			class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10"
			href="?page={{page_obj.previous_page_number}}"
			>Previous</a
		>
		{% endif %}
		<span
			class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10">
			Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
		</span>
		{% if page_obj.has_next %}
		<a
			class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10"
			href="?page={{page_obj.next_page_number}}"
			>Next</a
		>
		<a
			class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10"
			href="?page={{page_obj.paginator.num_pages}}"
			>Last</a
		>
		{% endif %}
	</span>
</div>
<!--Pagination Code ends here -->
{% endblock %}

myapp/app/templates/app/mylistings.html
{% extends 'app/base.html' %} {% block content %}
<div class="text-2xl m-10 p-10 font-bold">📄 My listings</div>
{% for product in products %}
<div class="itemcontainer flex shadow-lg m-10 p-10">
	<span class="w-1/5">
		<img class="w-40 h-40" src="{{product.image.url}}" alt="" />
	</span>
	<span class="w-2/5">
		<div class="font-bold text-gray-700">{{product.name}}</div>
		<div class="text-green-500">$ {{product.price}}</div>
		<div>{{product.desc}}</div>
	</span>
	<span class="w-1/5 my-10 mx-10">
		<a
			class="bg-green-500 text-white font-bold px-5 py-2"
			href="{% url 'app:update_product' product.id %}"
			>Edit</a
		>
	</span>
	<span class="w-1/5 my-10 mx-10">
		<a
			class="bg-red-500 text-white font-bold px-5 py-2"
			href="{% url 'app:delete_product' product.id %}"
			>Delete</a
		>
	</span>
</div>
{% endfor %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p> {{field.name}}{{ error }} </p>
        {% endfor %}
    {% endfor %}
{% endif %}
{% endblock %}

myapp/app/templates/app/product_confirm_delete.html
{% extends 'app/base.html' %}
{% block content  %}
<form method="POST">
	{% csrf_token %}
	<div class="rounded overflow-hidden shadow-lg h-100">
		<p class="font-bold text-lg">Are you sure you want to delete "{{ object }}" ?</p>
			<img class="w-1/6" src="{{product.image.url}}" alt="" />
			<div class="px-6 py-4">
				<div class="font-bold text-xl mb-2">{{product.name}}</div>
				<div class="font-bold text-xl text-green-500 mb-2">
					$ {{product.price}}
				</div>
				<div class="font-bold mb-2">
					Posted By:
					<span class="text-indigo-500">{{product.seller_name}}</span>
				</div>
				<p class="text-gray-700 text-base">{{product.desc}}</p>
				{{form}}
				<input class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800" type="submit" value="Confirm" name="" id="" />
			</div>
		</div>
</form>
{% endblock  %}

myapp/app/templates/app/product_form.html
{% extends 'app/base.html' %} {% block content %}
<h1 class="text-2xl m-10 font-bold">➕ Add Product</h1>
<form
	class="w-3/5 bg-white shadow-md m-10 px-8 py-8"
	method="POST"
	enctype="multipart/form-data"
>
	{% csrf_token %}
	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2" for=""
			>Product Name</label
		>

		<div
			class="shadow appearance-none border rounded w-1/4 py-2 px-3 mr-10 text-gray-700"
		>
			{{form.name}}
		</div>
	</div>

	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2" for=""
			>Product Price</label
		>

		<div
			class="shadow appearance-none border rounded w-1/4 py-2 px-3 mr-10 text-gray-700"
		>
			{{form.price}}
		</div>
	</div>
	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2" for=""
			>Product Description</label
		>

		<div
			class="shadow appearance-none border rounded w-1/4 py-2 px-3 mr-10 text-gray-700"
		>
			{{form.desc}}
		</div>
	</div>
	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2" for=""
			>Product Image</label
		>

		<div
			class="shadow appearance-none border rounded w-1/4 py-2 px-3 mr-10 text-gray-700"
		>
			{{form.image}}
		</div>
	</div>

	<div class="mb-4">
		<input
			class="bg-green-500 text-white px-5 py-2"
			type="submit"
			name="Add Product"
			value="Add Product"
			id=""
		/>
	</div>
</form>
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p> {{field.name}}{{ error }} </p>
        {% endfor %}
    {% endfor %}
{% endif %}
{% endblock %}

myapp/app/templates/app/product_update_form.html
{% extends 'app/base.html' %}

{% block content %}
<h1 class="text-2xl m-10 font-bold">Update Product</h1>
	<form class="w-3/5 bg-white shadow-md m-10 px-8 py-8"
		method="POST"
		enctype="multipart/form-data">
		{% csrf_token %}
		<div class="mb-4">
			<label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name</label>

			<div class="shadow appearance-none border rounded w-1/4 py-2 px-3 mr-10 text-gray-700">
				{{form.name}}
			</div>
		</div>

		<div class="mb-4">
			<label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Price</label>

			<div class="shadow appearance-none border rounded w-1/4 py-2 px-3 mr-10 text-gray-700">
				{{form.price}}
			</div>
		</div>
		<div class="mb-4">
			<label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Description</label>

			<div class="shadow appearance-none border rounded w-1/4 py-2 px-3 mr-10 text-gray-700">
				{{form.desc}}
			</div>
		</div>
		<div class="mb-4">
			<label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Image</label>
			<img class="w-1/4" src="{{product.image.url}}" alt="" />
			<div class="shadow appearance-none border rounded w-1/4 py-2 px-3 mr-10 text-gray-700">
				{{form.image}}
			</div>
		</div>

		<div class="mb-4">
			<input
				class="bg-green-500 text-white px-5 py-2"
				type="submit"
				name="Update Product"
				value="Update Product"
				id=""
			/>
		</div>
	</form>
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p class="text-red"> {{field.name}} {{ error }} </p>
        {% endfor %}
    {% endfor %}
{% endif %}
{% endblock %}

myapp/app/templates/app/search_results.html
{% extends 'app/base.html' %} {% block content %}
<div class="mt-4">
	{% if results %}
	<ul class="list-disc list-inside">
		{% for result in results %}
		<li>
			<a
				href="{% url 'app:product_detail' pk=result.pk %}"
				class="text-blue-500 hover:text-blue-700"
				>{{ result.name }}</a
			>
		</li>
		{% endfor %}
	</ul>
	{% else %}
	<p class="text-red-500">No results found for "{{ request.GET.q }}".</p>
	{% endif %}
</div>
{% endblock content %}

myapp/app/templates/app/updateproduct.html
{% extends 'app/base.html' %}

{% block content %}
<h1 class="text-2xl m-10 font-bold">➕ Update Product</h1>
<form class="w-3/5 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name</label>
		<input
			class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-700"
			placeholder="Computer"
			type="text"
			name="name"
			id="name"
			value="{{product.name}}"
		/>
	</div>
	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2" for="">
			Product Price</label>
		<input
			class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-700"
			placeholder=" 1000"
			type="text"
			name="price"
			id="price"
			value="{{product.price}}"
		/>
	</div>
	<div class="mb-4">
		<label class="block text-gray-700 text-sm font-bold mb-2" for="">
			Product Description</label
		>
		<input
			class="shadow apperance-none border rounded py-2 px-3 mr-10 text-gray-700"
			placeholder=" This is a Computer"
			type="text"
			name="desc"
			id="desc"
			value="{{product.desc}}"
		/>
	</div>
	<div class="mb-4">
		<img class="w-20 h-20" src="{{product.image.url}}" alt="" />
		<label class="block text-gray-700 text-sm font-bold mb-2" for="">
			Product Image
		</label>
		<input
			class="py-2"
			type="file"
			accept="image/*"
			name="upload"
			id="upload"
		/>
	</div>
	<div class="mb-4">
		<input
			class="bg-green-500 text-white px-5 py-2"
			type="submit"
			name="Update Product"
			value="Update Product"
			id=""
		/>
	</div>
</form>
{% endblock %}